<!DOCTYPE html>
<html>
<head>
	<title><?php echo $pageTitle; ?></title>
	<link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<style> 
	body{background-color: #e1ddcf;}
	h1{font-family: 'Satisfy', cursive; font-weight: 700; font-size:45px; text-align: center; margin: 0px, auto;}
	a{font-family: 'Satisfy', cursive; font-size: 25px; margin-left: 30px; color: #52199c; }
	p{font-family:sans-serif; color:#941818; text-align: center;}
	</style>
	
</head>
<body>
<p>A place to remember your favorite books</p> 